BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "components" (
	"comp_id"	INTEGER NOT NULL UNIQUE,
	"comp_name"	TEXT NOT NULL,
	"system_id"	INTEGER NOT NULL,
	PRIMARY KEY("comp_id" AUTOINCREMENT),
	FOREIGN KEY("system_id") REFERENCES "system"("system_id")
);
CREATE TABLE IF NOT EXISTS "division" (
	"div_id"	INTEGER NOT NULL UNIQUE,
	"div_name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("div_id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "object_type" (
	"type_id"	INTEGER NOT NULL UNIQUE,
	"industry"	TEXT NOT NULL,
	"purpose"	TEXT NOT NULL,
	"type_name"	TEXT NOT NULL,
	PRIMARY KEY("type_id")
);
CREATE TABLE IF NOT EXISTS "pd" (
	"pd_id"	INTEGER NOT NULL UNIQUE,
	"pd_name"	TEXT NOT NULL UNIQUE,
	"div_id"	INTEGER,
	PRIMARY KEY("pd_id" AUTOINCREMENT),
	FOREIGN KEY("div_id") REFERENCES "division"("div_id")
);
CREATE TABLE IF NOT EXISTS "rd" (
	"rd_id"	INTEGER NOT NULL UNIQUE,
	"rd_name"	TEXT NOT NULL,
	"rd_pref"	TEXT NOT NULL,
	"pd_name"	TEXT NOT NULL,
	PRIMARY KEY("rd_id" AUTOINCREMENT),
	FOREIGN KEY("pd_name") REFERENCES "pd"("pd_name")
);
CREATE TABLE IF NOT EXISTS "rd_budget_share" (
	"type_id"	INTEGER NOT NULL,
	"rd_id"	INTEGER NOT NULL,
	"budget_share"	REAL NOT NULL,
	PRIMARY KEY("type_id","rd_id"),
	FOREIGN KEY("rd_id") REFERENCES "rd"("rd_id"),
	FOREIGN KEY("type_id") REFERENCES "object_type"("type_id")
);
CREATE TABLE IF NOT EXISTS "system" (
	"system_id"	INTEGER NOT NULL UNIQUE,
	"system_name"	TEXT NOT NULL,
	"div_id"	INTEGER NOT NULL,
	"pd_id"	INTEGER NOT NULL,
	"rd_id"	INTEGER NOT NULL,
	PRIMARY KEY("system_id" AUTOINCREMENT),
	FOREIGN KEY("div_id") REFERENCES "division"("div_id"),
	FOREIGN KEY("pd_id") REFERENCES "pd"("pd_id"),
	FOREIGN KEY("rd_id") REFERENCES "rd"("rd_id")
);
CREATE TABLE IF NOT EXISTS "vendor" (
	"vendor_id"	INTEGER NOT NULL UNIQUE,
	"vendor_name"	TEXT NOT NULL,
	"div_id"	INTEGER NOT NULL,
	"project"	TEXT NOT NULL,
	"prior"	INTEGER NOT NULL,
	PRIMARY KEY("vendor_id" AUTOINCREMENT),
	FOREIGN KEY("div_id") REFERENCES "division"("div_id")
);
INSERT INTO "components" VALUES (1,'Силовой кабель и провод, провод СИП, арматура, муфты, трубы ПНД и комплектующие, гофрированная труба, плита ПЗК, кабельные лотки и комплектующие, сигнальная лента',1);
INSERT INTO "components" VALUES (2,'Дизельные электростанции',2);
INSERT INTO "components" VALUES (3,'Опоры и мачты освещения, кронштейны, осветительные комлексы',3);
INSERT INTO "components" VALUES (4,'Силовой кабель и провод, провод СИП, арматура, муфты, трубы ПНД и комплектующие, гофрированная труба, плита ПЗК, кабельные лотки и комплектующие, сигнальная лента',4);
INSERT INTO "components" VALUES (5,'Светильники консольные, торшерные, прожекторы, грунтовые, архитектурные, осветительные комплексы',5);
INSERT INTO "components" VALUES (6,'Датчики движения, датчики освещенности,таймеры, системы управления уличным освещением',6);
INSERT INTO "components" VALUES (7,'Корпуса пластиковые, корпуса металлические, шкафы металлические напольные, принадлежности для внутрищитового монтажа',7);
INSERT INTO "components" VALUES (8,'АВР (автоматический ввод резерва), выключатели нагрузки, рубильники, предохранители, котакторы, пускатели, реле, воздушные автоматические выключатели, частотные преобразователи, компенсация реактивной мощности',8);
INSERT INTO "components" VALUES (9,'Счетчики электроэнергии, трансформаторы измерительные',9);
INSERT INTO "components" VALUES (10,'Автоматические выключатели, устройства дифференциальной защиты, предохранители-разъединители, реле, котакторы, рубильники, переключатели, устройства от импульсных перенапряжений, дополнительные модульные устройства',10);
INSERT INTO "components" VALUES (11,'Розетки , выключатели, силовые разъемы , монтажные и распаечные коробки',11);
INSERT INTO "components" VALUES (12,'Кабель-каналы пластиковые, трубы пластиковые, трубы металлические, кабельные лотки и аксессуары',12);
INSERT INTO "components" VALUES (13,'Теплые полы и бытовой обогрев, терморегуляторы, кабель саморегулирующийся нагревательный, резистивный кабель, ругулирующая аппаратура(терморегуляторы, датчики',13);
INSERT INTO "components" VALUES (14,'Огнезащитные плиты, герметики, пены',14);
INSERT INTO "components" VALUES (15,'Шинопровод и комплектующие',15);
INSERT INTO "components" VALUES (16,'Корпуса пластиковые, корпуса металлические, шкафы металлические напольные, принадлежности для внутрищитового монтажа',16);
INSERT INTO "components" VALUES (17,'Автоматические выключатели, устройства дифференциальной защиты, предохранители-разъединители, реле, котакторы, рубильники, переключатели, устройства от импульсных перенапряжений, дополнительные модульные устройства',17);
INSERT INTO "components" VALUES (18,'Светильники встраиваемые, накладные, настенные, подвесные, настольные(напольные), светодиодные ленты,  блоки аварийного питания, эвакуационные указатели, драйверы (источники питания постоянным током)',18);
INSERT INTO "components" VALUES (19,'Датчики движения, датчики освещенности, датчики присутствия, система управления освещением DALI',19);
INSERT INTO "components" VALUES (20,'Изолированная молниезащита, молниеприемники и молниеотводы, сигнализаторы грозового разряда',20);
INSERT INTO "components" VALUES (21,'Комплекты заземления, элементы заземления (уголки, штыри, хомуты, муфты, винты, гайки, ГЗШ и пр), активное (электролитическое) заземление',21);
INSERT INTO "components" VALUES (22,'Противопожарные трубы и фасонные части',22);
INSERT INTO "components" VALUES (23,'Запорно-регулирующая арматура, арматура безопасности, КИП',22);
INSERT INTO "components" VALUES (24,'Установки пожаротушения',23);
INSERT INTO "components" VALUES (25,'Противопожарные шкафы и комплектующие (краны, рукава, огнетушители)',23);
INSERT INTO "components" VALUES (26,'Шкафы управления и сигнализации, датчики, пожарные резервуары',23);
INSERT INTO "components" VALUES (27,'Спринклеры и дренчеры',23);
INSERT INTO "components" VALUES (28,'Водоснабжение, водоотведение и дренаж, резервуары воды и системы отчистных сооружений',24);
INSERT INTO "components" VALUES (29,'Трубы и фасонные части',25);
INSERT INTO "components" VALUES (30,'Запорно-регулирующая арматура',25);
INSERT INTO "components" VALUES (31,'Кровельные воронки',26);
INSERT INTO "components" VALUES (32,'Греющие кабели и системы снеготаяния',26);
INSERT INTO "components" VALUES (33,'Установки повышения давления',27);
INSERT INTO "components" VALUES (34,'Трубы и фасонные части, изоляция',27);
INSERT INTO "components" VALUES (35,'Запорно-регулирующая арматура, арматура безопасности и балансировки',27);
INSERT INTO "components" VALUES (36,'Защита от протечек',27);
INSERT INTO "components" VALUES (37,'Узлы учета,коллекторы, гидроаккумуляторы, КИП',27);
INSERT INTO "components" VALUES (38,'Насосы циркуляции',28);
INSERT INTO "components" VALUES (39,'Трубы и фасонные части, изоляция',28);
INSERT INTO "components" VALUES (40,'Электрические и газовые котлы водоснабжения, бойлеры косвенные',28);
INSERT INTO "components" VALUES (41,'Запорно-регулирующая арматура, арматура безопасности и балансировки',28);
INSERT INTO "components" VALUES (42,'Узлы учета, этажные коллекторы, КИП, расширительные баки',28);
INSERT INTO "components" VALUES (43,'Канализационные насосы и установки',29);
INSERT INTO "components" VALUES (44,'Трубы и фасонные части, трапы и изоляция',29);
INSERT INTO "components" VALUES (45,'Водяные радиаторы (стальные, конвекторы, теплый пол)',30);
INSERT INTO "components" VALUES (46,'Электрические конвекторы и инфракрасные обогреватели',30);
INSERT INTO "components" VALUES (47,'Электрические и газовые котлы отопления ',30);
INSERT INTO "components" VALUES (48,'Термостатическое оборудование и насосы циркуляции отопления',30);
INSERT INTO "components" VALUES (49,'Трубы и фасонные части, изоляция',30);
INSERT INTO "components" VALUES (50,'Узлы учета, коллекторы отопления, коллекторные шкафы, расширительные баки',30);
INSERT INTO "components" VALUES (51,'Запорно-регулирующая арматура, арматура безопасности, КИП',30);
INSERT INTO "components" VALUES (52,'Воздуховоды и фасонные элементы',31);
INSERT INTO "components" VALUES (53,'Решетки, диффузоры, воздухораспределители',31);
INSERT INTO "components" VALUES (54,'Дроссели, клапана обычные, заслонки, привода',31);
INSERT INTO "components" VALUES (55,'Клапана огнезащитные',31);
INSERT INTO "components" VALUES (56,'Приточные и приточно-вытяжные установки',31);
INSERT INTO "components" VALUES (57,'Бытовые вытяжные вентиляторы',31);
INSERT INTO "components" VALUES (58,'Вентиляторы (ВО, ВР, ВЦ, ВКР), вентиляторы дымоудаления, взрывозащищенные',31);
INSERT INTO "components" VALUES (59,'Вентиляторы канальные (ВКО, ВКП)',31);
INSERT INTO "components" VALUES (60,'Зонты, зонты островные',31);
INSERT INTO "components" VALUES (61,'Наборная вентиляция (Нагреватели, калориферы, охладители, шумоглушители и т.д.) ЕСЛИ ОНИ НЕ В СОСТАВЕ ВЕНТ СИСТЕМЫ!',31);
INSERT INTO "components" VALUES (62,'Огнезащита (МБОР и т.п.)',31);
INSERT INTO "components" VALUES (63,'Тепловые завесы и обвязка',31);
INSERT INTO "components" VALUES (64,'Тепловентиляторы (пром., не бытовые) и обвязка',31);
INSERT INTO "components" VALUES (65,'Бризеры/КИВ',31);
INSERT INTO "components" VALUES (66,'Кондиционеры (Бытовые сплит-системы)',31);
INSERT INTO "components" VALUES (67,'Кондиционеры (Мульти, канальные, кассетные, напольные, напольно-потолочные)',31);
INSERT INTO "components" VALUES (68,'VRF/VRV-системы, чиллер-фанкойлы',31);
INSERT INTO "components" VALUES (69,'Автоматизированные тепловые пункты',32);
INSERT INTO "components" VALUES (70,'Теплообменники, узлы учета, запорно-регулирующая арматура, КИП',33);
INSERT INTO "components" VALUES (71,'В составе тепловых пунктов и магистральных теплосетей',34);
INSERT INTO "components" VALUES (72,'IP АТС, SIP-серверы, телефоны, сопутствующее ПО, слаботочный кабель (сКПП), аксессуары',35);
INSERT INTO "components" VALUES (73,'Конвертеры IP/СПВ, акссесуары',36);
INSERT INTO "components" VALUES (74,'Усилители приема, делители/аттенюаторы, антенны, аксессуары',37);
INSERT INTO "components" VALUES (75,'Шкафы, PDU, управление климатом, кабельные органайзеры, полки, щеточные вводы, фальш-панели, заземление, освещение, ИБП, Стабилизаторы',38);
INSERT INTO "components" VALUES (76,'Витая пара',39);
INSERT INTO "components" VALUES (77,'Оптико-волоконные кабели',39);
INSERT INTO "components" VALUES (78,'Медные компоненты: Патч-панели, патч-корды, разъемы, розетки, соединители',40);
INSERT INTO "components" VALUES (79,'Оптические компоненты: Кроссы, патч-корды, пигтейлы, разъемы, муфты',40);
INSERT INTO "components" VALUES (80,'Контроллеры, КИП, SCADA, модули контроля/управления, фурнитура',41);
INSERT INTO "components" VALUES (81,'Контроллеры, КИП, SCADA, модули контроля/управления',42);
INSERT INTO "components" VALUES (82,'Контроллеры, КИП, SCADA, электродвигатели, частотники, модули контроля/управления, фурнитура',43);
INSERT INTO "components" VALUES (83,'Видеокамеры, видеорегистраторы, коробки, кабель для видеонаблюдения (КВК)',44);
INSERT INTO "components" VALUES (84,'Видеосерверы, ПО, слаботочный кабель',45);
INSERT INTO "components" VALUES (85,'Коммутаторы и слаботочный кабель сКПП (Если у СВН своя ЛВС), жесткие диски, блоки питания, ИБП, Стабилизаторы',46);
INSERT INTO "components" VALUES (86,'Контрольные панели, извещатели, оповещатели, блоки контроля шлейфов',47);
INSERT INTO "components" VALUES (87,'Контрольные панели, извещатели, оповещатели, блоки контроля шлейфов',48);
INSERT INTO "components" VALUES (88,'Контроллеры, считыватели, ПО',49);
INSERT INTO "components" VALUES (89,'Турникеты, шлагбаумы, калитки',50);
INSERT INTO "components" VALUES (90,'Металлодетекторы, доводчики, замки, кнопки, блоки питания, досмотровые устройства',51);
INSERT INTO "components" VALUES (91,'Фискальные регистраторы, смарт кассы, принтеры чеков, денежные ящики, POS-оборудование, кассы самообслуживания',52);
INSERT INTO "components" VALUES (92,'Детекторы банкнот, счетчики банкнот, сортировщики банкнот, упаковщики банкнот, счетчики монет, сортировщики монет, темпокассы',53);
INSERT INTO "components" VALUES (93,'Сканеры штрих-кода, теминалы сбора данных (ТСД), принтеры этикеток',54);
INSERT INTO "components" VALUES (94,'Весы торговые, фасовочные, лабораторные',55);
INSERT INTO "components" VALUES (95,'Коммутаторы, промышленные коммутаторы, СХД, маршрутизаторы, аксессуары и сопутствующее оборудование',56);
INSERT INTO "components" VALUES (96,'Серверы для ЦОД, серверы времени, терминальные серверы, серверы баз данных, СХД, АРМ, комплектующие для серверов',57);
INSERT INTO "components" VALUES (97,'Серверы для ЦОД, серверы времени, терминальные серверы, серверы баз данных, СХД, АРМ, комплектующие для серверов',58);
INSERT INTO "components" VALUES (98,'Системное ПО, офсиное ПО, прикладное ПО, базы-данных, 1С, ключи активации и верификации',59);
INSERT INTO "components" VALUES (99,'Терминалы, серверы ВКС, видеокамеры трансляции, дисплеи, микрофоны, спикрефоны, динамики, ПО ВКС',60);
INSERT INTO "components" VALUES (100,'Проекторы, экраны, ЖК-дисплеи, OLED-панел, видеостены, видеоконтроллеры, панели управления, коммутационный кабель аудио- видеосигнала',61);
INSERT INTO "components" VALUES (101,'Контрольные приборы (ППКОП), извещатели, модули управления/контроля, блоки питания, блоки управления и индикации',62);
INSERT INTO "components" VALUES (102,'Элементы стоечных систем оповещения (Rack), моноблоки, оповещатели речевые, оповещатели звуковые/световые, усилители трансляционные, модули контроля линий',63);
INSERT INTO "components" VALUES (103,'Элементы ОКЛ:  КНС, крепежные аксессуары, огнестойкие коммутационные коробки',64);
INSERT INTO "components" VALUES (104,'Элементы ОКЛ:  КНС, крепежные аксессуары, огнестойкие коммутационные коробки',65);
INSERT INTO "components" VALUES (105,'Модули управления/контроля, модули управления клапанами, контрольные приборы, блоки индикации и управления',66);
INSERT INTO "components" VALUES (106,'Модули управления/контроля, контрольные приборы, блоки индикации и управления, модули пожаротушения, шкафы управления двигателями/задвижками, извещатели, КИП',67);
INSERT INTO "components" VALUES (107,'Противопожарные шкафы и комплектующие (краны, рукава, огнетушители); шкафы управления и сигнализации, датчики, пожарные резервуары; спринклеры и дренчеры',68);
INSERT INTO "division" VALUES (1,'ДЭ');
INSERT INTO "division" VALUES (2,'ДИСиК');
INSERT INTO "division" VALUES (3,'ДССиСА');
INSERT INTO "object_type" VALUES (10101,'Транспортная инфраструктура','Вокзал ж/д','Вокзал ж/д');
INSERT INTO "object_type" VALUES (10201,'Транспортная инфраструктура','Вокзал авто','Вокзал авто');
INSERT INTO "object_type" VALUES (10301,'Транспортная инфраструктура','Аэропорт, аэродром','ВПП, рулежные дорожки, перроны');
INSERT INTO "object_type" VALUES (10302,'Транспортная инфраструктура','Аэропорт, аэродром','Аэровокзальный комплекс');
INSERT INTO "object_type" VALUES (10401,'Транспортная инфраструктура','Порт речной','Пассажирский');
INSERT INTO "object_type" VALUES (10402,'Транспортная инфраструктура','Порт речной','Грузовой');
INSERT INTO "object_type" VALUES (10501,'Транспортная инфраструктура','Порт морской','Пассажирский');
INSERT INTO "object_type" VALUES (10502,'Транспортная инфраструктура','Порт морской','Грузовой');
INSERT INTO "object_type" VALUES (10601,'Транспортная инфраструктура','Гидротехническое сооружение','Гидротехническое сооружение');
INSERT INTO "object_type" VALUES (10701,'Транспортная инфраструктура','Автомагистраль/автодорога','Трасса с освещением полотна');
INSERT INTO "object_type" VALUES (10801,'Транспортная инфраструктура','Мост','Мост');
INSERT INTO "object_type" VALUES (10901,'Транспортная инфраструктура','Тоннель','Тоннель');
INSERT INTO "object_type" VALUES (11001,'Транспортная инфраструктура','Транспортная развязка','Транспортная развязка, эстакада, виадук');
INSERT INTO "object_type" VALUES (11201,'Транспортная инфраструктура','Метрополитен','Подземный вестибюль станции');
INSERT INTO "object_type" VALUES (11202,'Транспортная инфраструктура','Метрополитен','Наземный вестибюль станции');
INSERT INTO "object_type" VALUES (11203,'Транспортная инфраструктура','Метрополитен','Пересадочная станция');
INSERT INTO "object_type" VALUES (11204,'Транспортная инфраструктура','Метрополитен','Электродепо');
INSERT INTO "object_type" VALUES (11205,'Транспортная инфраструктура','Метрополитен','База по ремонту эскалаторов');
INSERT INTO "object_type" VALUES (11206,'Транспортная инфраструктура','Метрополитен','База подъемного ремонта вагонов');
INSERT INTO "object_type" VALUES (11301,'Транспортная инфраструктура','Гаражные и парковочные комплексы','Гаражные и парковочные комплексы');
INSERT INTO "object_type" VALUES (11401,'Транспортная инфраструктура','Ж/д депо','Ж/д депо, парки ремонта и обслуживания');
INSERT INTO "object_type" VALUES (11501,'Транспортная инфраструктура','Судно/Корабль','Судно/Корабль');
INSERT INTO "object_type" VALUES (11601,'Транспортная инфраструктура','Железная дорога','Железная дорога');
INSERT INTO "object_type" VALUES (19901,'Транспортная инфраструктура','Прочие объекты ТИ','Прочие объекты отрасли ТИ');
INSERT INTO "object_type" VALUES (20101,'Нефтегаз проекты','НПЗ','НПЗ');
INSERT INTO "object_type" VALUES (20201,'Нефтегаз проекты','КС','Головная КС');
INSERT INTO "object_type" VALUES (20202,'Нефтегаз проекты','КС','Линейная КС');
INSERT INTO "object_type" VALUES (20203,'Нефтегаз проекты','КС','Дожимная КС');
INSERT INTO "object_type" VALUES (20204,'Нефтегаз проекты','КС','Распределенная КС');
INSERT INTO "object_type" VALUES (20301,'Нефтегаз проекты','Нефтяной терминал','Распределительный');
INSERT INTO "object_type" VALUES (20302,'Нефтегаз проекты','Нефтяной терминал','Перевалочный');
INSERT INTO "object_type" VALUES (20303,'Нефтегаз проекты','Нефтяной терминал','Универсальный');
INSERT INTO "object_type" VALUES (20401,'Нефтегаз проекты','Насосная станция','Насосная станция');
INSERT INTO "object_type" VALUES (20501,'Нефтегаз проекты','Трубопровод','Трубопровод');
INSERT INTO "object_type" VALUES (20601,'Нефтегаз проекты','Месторождение','Месторождение');
INSERT INTO "object_type" VALUES (20701,'Нефтегаз проекты','Хранилища и ТСБ','Нефтегазовые хранилища');
INSERT INTO "object_type" VALUES (20702,'Нефтегаз проекты','Хранилища и ТСБ','Нефтегазовые товарно-сырьевые базы');
INSERT INTO "object_type" VALUES (20801,'Нефтегаз проекты','АЗС','Стационарная');
INSERT INTO "object_type" VALUES (20802,'Нефтегаз проекты','АЗС','Контейнерная');
INSERT INTO "object_type" VALUES (20803,'Нефтегаз проекты','АЗС','Модульная');
INSERT INTO "object_type" VALUES (20804,'Нефтегаз проекты','АЗС','Передвижная');
INSERT INTO "object_type" VALUES (20901,'Нефтегаз проекты','Химическое производство','Химическое и нефтехимическое производство');
INSERT INTO "object_type" VALUES (29901,'Нефтегаз проекты','Прочие объекты НГ','Прочие объекты отрасли НГ');
INSERT INTO "object_type" VALUES (30101,'Торговые сети и коммерческая недвижимость','Торговые сети','Премиум-сегмент');
INSERT INTO "object_type" VALUES (30102,'Торговые сети и коммерческая недвижимость','Торговые сети','Масс-маркет');
INSERT INTO "object_type" VALUES (30103,'Торговые сети и коммерческая недвижимость','Торговые сети','Дискаунтер');
INSERT INTO "object_type" VALUES (30201,'Торговые сети и коммерческая недвижимость','ТРЦ','Класс A (наивысший)');
INSERT INTO "object_type" VALUES (30202,'Торговые сети и коммерческая недвижимость','ТРЦ','Класс B');
INSERT INTO "object_type" VALUES (30203,'Торговые сети и коммерческая недвижимость','ТРЦ','Класс C (низший)');
INSERT INTO "object_type" VALUES (30301,'Торговые сети и коммерческая недвижимость','Бизнес-центр','Класс A (наивысший)');
INSERT INTO "object_type" VALUES (30302,'Торговые сети и коммерческая недвижимость','Бизнес-центр','Класс B');
INSERT INTO "object_type" VALUES (30303,'Торговые сети и коммерческая недвижимость','Бизнес-центр','Класс C');
INSERT INTO "object_type" VALUES (30304,'Торговые сети и коммерческая недвижимость','Бизнес-центр','Класс D (низший)');
INSERT INTO "object_type" VALUES (30401,'Торговые сети и коммерческая недвижимость','Гостиницы','Без категории');
INSERT INTO "object_type" VALUES (30402,'Торговые сети и коммерческая недвижимость','Гостиницы','Категория *');
INSERT INTO "object_type" VALUES (30403,'Торговые сети и коммерческая недвижимость','Гостиницы','Категория **');
INSERT INTO "object_type" VALUES (30404,'Торговые сети и коммерческая недвижимость','Гостиницы','Категория ***');
INSERT INTO "object_type" VALUES (30405,'Торговые сети и коммерческая недвижимость','Гостиницы','Категория ****');
INSERT INTO "object_type" VALUES (30406,'Торговые сети и коммерческая недвижимость','Гостиницы','Категория *****');
INSERT INTO "object_type" VALUES (30501,'Торговые сети и коммерческая недвижимость','Логистический комплекс','Логистический комплекс, распределительный центр');
INSERT INTO "object_type" VALUES (30801,'Торговые сети и коммерческая недвижимость','Аква-парки','Аква-парки, SPA-комплексы');
INSERT INTO "object_type" VALUES (30901,'Торговые сети и коммерческая недвижимость','Театры, кинотеатры','Театры, кинотеатры, концертные залы');
INSERT INTO "object_type" VALUES (31001,'Торговые сети и коммерческая недвижимость','Парки аттракционов','Парки аттракционов, развлечений');
INSERT INTO "object_type" VALUES (31101,'Торговые сети и коммерческая недвижимость','Рекреационные комплексы','Рекреационно-туристические комплексы');
INSERT INTO "object_type" VALUES (39901,'Торговые сети и коммерческая недвижимость','Прочие объекты','Прочие объекты коммерческой недвижимости');
INSERT INTO "object_type" VALUES (40101,'Социальная инфраструктура','ЖК','Эконом-класс');
INSERT INTO "object_type" VALUES (40102,'Социальная инфраструктура','ЖК','Бизнес-класс');
INSERT INTO "object_type" VALUES (40103,'Социальная инфраструктура','ЖК','Элитный-класс');
INSERT INTO "object_type" VALUES (40201,'Социальная инфраструктура','ДОУ','Муниципальный');
INSERT INTO "object_type" VALUES (40202,'Социальная инфраструктура','ДОУ','Ведомственный');
INSERT INTO "object_type" VALUES (40203,'Социальная инфраструктура','ДОУ','Частный');
INSERT INTO "object_type" VALUES (40301,'Социальная инфраструктура','СОШ','Муниципальный');
INSERT INTO "object_type" VALUES (40302,'Социальная инфраструктура','СОШ','Ведомственный');
INSERT INTO "object_type" VALUES (40303,'Социальная инфраструктура','СОШ','Частный');
INSERT INTO "object_type" VALUES (40401,'Социальная инфраструктура','ВУЗ','Государственное');
INSERT INTO "object_type" VALUES (40402,'Социальная инфраструктура','ВУЗ','Частное');
INSERT INTO "object_type" VALUES (40801,'Социальная инфраструктура','Музей, библиотека','Объект местного значения');
INSERT INTO "object_type" VALUES (40802,'Социальная инфраструктура','Музей, библиотека','Объект регионального значения');
INSERT INTO "object_type" VALUES (40803,'Социальная инфраструктура','Музей, библиотека','Объект Федерального значения');
INSERT INTO "object_type" VALUES (40804,'Социальная инфраструктура','Музей, библиотека','Объект Всемирного значения');
INSERT INTO "object_type" VALUES (40901,'Социальная инфраструктура','Детские лагеря','Детский лагерь');
INSERT INTO "object_type" VALUES (40902,'Социальная инфраструктура','Детские центры','Развивающие, творческие центры');
INSERT INTO "object_type" VALUES (40903,'Социальная инфраструктура','Пансионаты','Пансионаты для детей');
INSERT INTO "object_type" VALUES (49901,'Социальная инфраструктура','Прочие объекты СИ','Прочие объекты отрасли СИ');
INSERT INTO "object_type" VALUES (50101,'Электроэнергетика','КЭС','Конденсационная электростанция');
INSERT INTO "object_type" VALUES (50201,'Электроэнергетика','ТЭЦ','Теплоэлектростанция');
INSERT INTO "object_type" VALUES (50301,'Электроэнергетика','АЭС','Атомная электростанция');
INSERT INTO "object_type" VALUES (50401,'Электроэнергетика','ГЭС','Гидроэлектростанция');
INSERT INTO "object_type" VALUES (50501,'Электроэнергетика','ВИЭ','Энергия ветра');
INSERT INTO "object_type" VALUES (50502,'Электроэнергетика','ВИЭ','Энергия воды');
INSERT INTO "object_type" VALUES (50503,'Электроэнергетика','ВИЭ','Энергия солнечного света');
INSERT INTO "object_type" VALUES (50504,'Электроэнергетика','ВИЭ','Энергия земли');
INSERT INTO "object_type" VALUES (50505,'Электроэнергетика','ВИЭ','Прочие (Биоэнергия)');
INSERT INTO "object_type" VALUES (50601,'Электроэнергетика','ВЛ','Низковольтные линии (до 1 кВ)');
INSERT INTO "object_type" VALUES (50602,'Электроэнергетика','ВЛ','Линии среднего напряжения (3-35 кВ)');
INSERT INTO "object_type" VALUES (50603,'Электроэнергетика','ВЛ','Линии высокого напряжения (110-220 кВ)');
INSERT INTO "object_type" VALUES (50604,'Электроэнергетика','ВЛ','Линии сверхвысокого напряжения (330 кВ+)');
INSERT INTO "object_type" VALUES (50605,'Электроэнергетика','ВЛ','ВОЛС');
INSERT INTO "object_type" VALUES (50701,'Электроэнергетика','КЛ','Низковольтные КЛ (до 1 кВ)');
INSERT INTO "object_type" VALUES (50702,'Электроэнергетика','КЛ','КЛ среднего напряжения (3-35 кВ)');
INSERT INTO "object_type" VALUES (50703,'Электроэнергетика','КЛ','КЛ высокого напряжения (110-220 кВ)');
INSERT INTO "object_type" VALUES (50704,'Электроэнергетика','КЛ','КЛ сверхвысокого напряжения (330 кВ+)');
INSERT INTO "object_type" VALUES (50705,'Электроэнергетика','КЛ','ВОЛС');
INSERT INTO "object_type" VALUES (50801,'Электроэнергетика','ТП','ТП на напряжение 6-35/0,4 кВ');
INSERT INTO "object_type" VALUES (50802,'Электроэнергетика','ТП','ТП на напряжение 35/6-10 кВ');
INSERT INTO "object_type" VALUES (50803,'Электроэнергетика','ТП','ТП на напряжение 110-220/6-35 кВ');
INSERT INTO "object_type" VALUES (50804,'Электроэнергетика','ТП','ТП с первичным напряжением 330 кВ+');
INSERT INTO "object_type" VALUES (50901,'Электроэнергетика','Прочие ЭЭ','Низковольтные ЭЭ объекты (до 1 кВ)');
INSERT INTO "object_type" VALUES (50902,'Электроэнергетика','Прочие ЭЭ','ЭЭ объекты среднего напряжения (3-35 кВ)');
INSERT INTO "object_type" VALUES (50903,'Электроэнергетика','Прочие ЭЭ','ЭЭ объекты высокого напряжения (110-220 кВ)');
INSERT INTO "object_type" VALUES (50904,'Электроэнергетика','Прочие ЭЭ','ЭЭ объекты сверхвысокого напряжения (330 кВ+)');
INSERT INTO "object_type" VALUES (60101,'Промышленность','Судостроительный завод','Судостроительный/судоремонтный завод');
INSERT INTO "object_type" VALUES (60301,'Промышленность','Черная металлургия','Гидрометаллургическое производство');
INSERT INTO "object_type" VALUES (60302,'Промышленность','Черная металлургия','Пирометаллургическое производство');
INSERT INTO "object_type" VALUES (60303,'Промышленность','Черная металлургия','Прочее металлургическое производство');
INSERT INTO "object_type" VALUES (60401,'Промышленность','Цветная металлургия','Производство Цветной металлургии');
INSERT INTO "object_type" VALUES (60601,'Промышленность','Авиакосмическая промышленность','Производство космической/авиационной промышленности');
INSERT INTO "object_type" VALUES (60701,'Промышленность','Машиностроение','Общее машиностроение и металлообработка');
INSERT INTO "object_type" VALUES (60801,'Промышленность','Лесная промышленность','Лесная, деревообрабатывающая и ЦБП');
INSERT INTO "object_type" VALUES (60901,'Промышленность','Стройматериалы','Производство строительных материалов');
INSERT INTO "object_type" VALUES (61001,'Промышленность','Легкая промышленность','Предприятие лёгкой промышленности');
INSERT INTO "object_type" VALUES (61101,'Промышленность','Стекольное производство','Стекольное и фарфорофаянсовое производство');
INSERT INTO "object_type" VALUES (61201,'Промышленность','Фармацевтика','Микробиологическое, фармацевтическое производство');
INSERT INTO "object_type" VALUES (61301,'Промышленность','Медицинская промышленность','Производство медицинской промышленности');
INSERT INTO "object_type" VALUES (61401,'Промышленность','Полиграфия','Полиграфическое производство');
INSERT INTO "object_type" VALUES (61701,'Промышленность','Добыча ископаемых','Добыча и переработка полезных ископаемых');
INSERT INTO "object_type" VALUES (61801,'Промышленность','Химическая промышленность','Химическая промышленность');
INSERT INTO "object_type" VALUES (61901,'Промышленность','Автопром','Производство автомобилей и автокомпонентов');
INSERT INTO "object_type" VALUES (62001,'Промышленность','Пищевая промышленность','Предприятие пищевой промышленности');
INSERT INTO "object_type" VALUES (62101,'Промышленность','Сельхозмашиностроение','Предприятие сельскохозяйственного машиностроения');
INSERT INTO "object_type" VALUES (62201,'Промышленность','Авиастроение','Авиастроительное предприятие');
INSERT INTO "object_type" VALUES (69901,'Промышленность','Прочие производства','Прочие производственные отрасли');
INSERT INTO "object_type" VALUES (70101,'Телекоммуникации и IT-инфраструктура','ЦОД','Tier I - базовая инфраструктура');
INSERT INTO "object_type" VALUES (70102,'Телекоммуникации и IT-инфраструктура','ЦОД','Tier II - с резервными мощностями');
INSERT INTO "object_type" VALUES (70103,'Телекоммуникации и IT-инфраструктура','ЦОД','Tier III - параллельный ремонт');
INSERT INTO "object_type" VALUES (70104,'Телекоммуникации и IT-инфраструктура','ЦОД','Tier IV - отказоустойчивая');
INSERT INTO "object_type" VALUES (70201,'Телекоммуникации и IT-инфраструктура','Узел связи','Узел/станция спутниковой связи');
INSERT INTO "object_type" VALUES (70202,'Телекоммуникации и IT-инфраструктура','Узел связи','Распределительный узел/станция');
INSERT INTO "object_type" VALUES (70203,'Телекоммуникации и IT-инфраструктура','Узел связи','Телекоммуникационная вышка/узел');
INSERT INTO "object_type" VALUES (70204,'Телекоммуникации и IT-инфраструктура','Узел связи','Ретрансляционный узел/станция');
INSERT INTO "object_type" VALUES (70301,'Телекоммуникации и IT-инфраструктура','Диспетчерский центр','Диспетчерский/мониторинговый центр');
INSERT INTO "object_type" VALUES (79901,'Телекоммуникации и IT-инфраструктура','Прочие объекты','Прочие объекты телеком. и IT-инфраструктуры');
INSERT INTO "object_type" VALUES (80101,'Медицинские объекты','Поликлиника','Поликлиника');
INSERT INTO "object_type" VALUES (80201,'Медицинские объекты','Госпиталь','Госпиталь/больница');
INSERT INTO "object_type" VALUES (80301,'Медицинские объекты','Медцентр','Многофункциональный медицинский центр');
INSERT INTO "object_type" VALUES (80401,'Медицинские объекты','Перинатальный центр','Перинатальный центр');
INSERT INTO "object_type" VALUES (80501,'Медицинские объекты','Дом престарелых','Дом престарелых');
INSERT INTO "object_type" VALUES (80601,'Медицинские объекты','Лечебно-оздоровительный комплекс','Лечебно-оздоровительный комплекс');
INSERT INTO "object_type" VALUES (80701,'Медицинские объекты','Реабилитационный центр','Реабилитационный центр');
INSERT INTO "object_type" VALUES (80801,'Медицинские объекты','Интернат','Интернат для инвалидов');
INSERT INTO "object_type" VALUES (80901,'Медицинские объекты','Лаборатория','Лаборатория');
INSERT INTO "object_type" VALUES (89901,'Медицинские объекты','Прочие мед.объекты','Прочие мед.объекты');
INSERT INTO "object_type" VALUES (90101,'Спортивные объекты','Стадион','Открытая арена');
INSERT INTO "object_type" VALUES (90201,'Спортивные объекты','Стадион','Закрытая арена');
INSERT INTO "object_type" VALUES (90301,'Спортивные объекты','Плавательный комплекс','Многофункциональный плавательный комплекс');
INSERT INTO "object_type" VALUES (90401,'Спортивные объекты','Бассейн','Бассейн');
INSERT INTO "object_type" VALUES (90501,'Спортивные объекты','Ледовая арена','Ледовая арена');
INSERT INTO "object_type" VALUES (90601,'Спортивные объекты','Ледовый дворец','Ледовый дворец');
INSERT INTO "object_type" VALUES (90701,'Спортивные объекты','ФОК','Физкультурно-оздоровительный комплекс');
INSERT INTO "object_type" VALUES (90801,'Спортивные объекты','Спортивный клуб','Спортивный клуб');
INSERT INTO "object_type" VALUES (110101,'Объекты военной инфраструктуры','Структурные подразделения ВС','Структурные подразделения ВС');
INSERT INTO "object_type" VALUES (110201,'Объекты военной инфраструктуры','Оборонная промышленность','Предприятия оборонной промышленности');
INSERT INTO "object_type" VALUES (110301,'Объекты военной инфраструктуры','НИЦ ВПК','Научно-исследовательские центры ВПК');
INSERT INTO "object_type" VALUES (119901,'Объекты военной инфраструктуры','Прочие объекты','Прочие объекты военной инфраструктуры');
INSERT INTO "object_type" VALUES (120101,'Агропромышленность','Интегрированные с/х','Интегрированные с/х предприятия');
INSERT INTO "object_type" VALUES (120201,'Агропромышленность','Растениеводство','Растениеводческие предприятия');
INSERT INTO "object_type" VALUES (120301,'Агропромышленность','Животноводство','Животноводческие предприятия');
INSERT INTO "object_type" VALUES (120401,'Агропромышленность','Аквакультура','Рыбоводство, аквакультура');
INSERT INTO "object_type" VALUES (120501,'Агропромышленность','Хранение с/х продукции','Хранение и переработка с/х продукции');
INSERT INTO "object_type" VALUES (129901,'Агропромышленность','Прочие с/х','Прочие с/х предприятия');
INSERT INTO "object_type" VALUES (990101,'Не определено','Не определено','Не определено');
INSERT INTO "pd" VALUES (1,'Система электроснабжения',1);
INSERT INTO "pd" VALUES (2,'Водоснабжение и канализация',2);
INSERT INTO "pd" VALUES (3,'Отопление, вентиляция и кондиционирование',2);
INSERT INTO "pd" VALUES (4,'Сети связи',3);
INSERT INTO "pd" VALUES (5,'Мероприятия по обеспечению пожарной безопасности',3);
INSERT INTO "rd" VALUES (1,'Электроснабжение','ЭС','Система электроснабжения');
INSERT INTO "rd" VALUES (2,'Наружное  электроосвещение','ЭН','Система электроснабжения');
INSERT INTO "rd" VALUES (3,'Силовое  электрооборудование','ЭМ','Система электроснабжения');
INSERT INTO "rd" VALUES (4,'Внутреннее  электроосвещение','ЭО','Система электроснабжения');
INSERT INTO "rd" VALUES (5,'Молниезащита  и  заземление','ЭГ','Система электроснабжения');
INSERT INTO "rd" VALUES (6,'Противопожарный водопровод и системы противопожарной защиты','ВК','Водоснабжение и канализация');
INSERT INTO "rd" VALUES (7,'Противопожарный водопровод и системы противопожарной защиты','АУПТ','Водоснабжение и канализация');
INSERT INTO "rd" VALUES (8,'Наружные водостоки и ливневая канализация, сети водоснабжения','ВК','Водоснабжение и канализация');
INSERT INTO "rd" VALUES (9,'Водоснабжение и канализация','ВК','Водоснабжение и канализация');
INSERT INTO "rd" VALUES (10,'Отопление, вентиляция, кондиционирование, тепловые сети','ОВ','Отопление, вентиляция и кондиционирование');
INSERT INTO "rd" VALUES (11,'Теплоснабжение, тепловые пункты и узлы учета','ИТП','Отопление, вентиляция и кондиционирование');
INSERT INTO "rd" VALUES (12,'Телефония, Радиофикация, Телеприем','РТ','Сети связи');
INSERT INTO "rd" VALUES (13,'Структурированные кабельные сети','СКС','Сети связи');
INSERT INTO "rd" VALUES (14,'Автоматизация инженерных систем','АСУД','Сети связи');
INSERT INTO "rd" VALUES (15,'Автоматизация инженерных систем','АСКЗ','Сети связи');
INSERT INTO "rd" VALUES (16,'Автоматизация инженерных систем','АК','Сети связи');
INSERT INTO "rd" VALUES (17,'Видеонаблюдение','ВН','Сети связи');
INSERT INTO "rd" VALUES (18,'Охранная сигнализация','ОС','Сети связи');
INSERT INTO "rd" VALUES (19,'Система контроля и учета доступа','СКУД','Сети связи');
INSERT INTO "rd" VALUES (20,'Торговое оборудование','ТО','Сети связи');
INSERT INTO "rd" VALUES (21,'Локальные Вычислительные Системы (ЛВС)','АСО','Сети связи');
INSERT INTO "rd" VALUES (22,'Локальные Вычислительные Системы (ЛВС)','КО','Сети связи');
INSERT INTO "rd" VALUES (23,'Локальные Вычислительные Системы (ЛВС)','ПО','Сети связи');
INSERT INTO "rd" VALUES (24,'Локальные Вычислительные Системы (ЛВС)','МК','Сети связи');
INSERT INTO "rd" VALUES (25,'Автоматическая установка пожарной сигнализации','АПС','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd" VALUES (26,'Система оповещения и управления эвакуацией людей при пожаре','СОУЭ','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd" VALUES (27,'Автоматическая установка пожарной сигнализации','ОКЛ','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd" VALUES (28,'Система оповещения и управления эвакуацией людей при пожаре','ОКЛ','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd" VALUES (29,'Автоматика противопожарной защиты','АППЗ','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd" VALUES (30,'Спецпожаротушение','АПТ','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd" VALUES (31,'Противопожарный водопровод и системы противопожарной защиты','ПТ','Мероприятия по обеспечению пожарной безопасности');
INSERT INTO "rd_budget_share" VALUES (10101,1,2.7);
INSERT INTO "rd_budget_share" VALUES (10101,3,2.7);
INSERT INTO "rd_budget_share" VALUES (10101,5,1.5);
INSERT INTO "rd_budget_share" VALUES (10101,2,0.1);
INSERT INTO "rd_budget_share" VALUES (10101,4,0.6);
INSERT INTO "rd_budget_share" VALUES (10101,13,0.4);
INSERT INTO "rd_budget_share" VALUES (10101,17,0.25);
INSERT INTO "rd_budget_share" VALUES (10101,19,0.2);
INSERT INTO "rd_budget_share" VALUES (10101,18,0.7);
INSERT INTO "rd_budget_share" VALUES (10101,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10101,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10101,10,0.7);
INSERT INTO "rd_budget_share" VALUES (10101,8,0.7);
INSERT INTO "rd_budget_share" VALUES (10101,9,1.7);
INSERT INTO "rd_budget_share" VALUES (10101,11,0.2);
INSERT INTO "rd_budget_share" VALUES (10101,16,1.05);
INSERT INTO "rd_budget_share" VALUES (10101,20,0.2);
INSERT INTO "rd_budget_share" VALUES (10201,1,2.5);
INSERT INTO "rd_budget_share" VALUES (10201,3,2.5);
INSERT INTO "rd_budget_share" VALUES (10201,5,1.4);
INSERT INTO "rd_budget_share" VALUES (10201,2,0.1);
INSERT INTO "rd_budget_share" VALUES (10201,4,0.5);
INSERT INTO "rd_budget_share" VALUES (10201,13,0.4);
INSERT INTO "rd_budget_share" VALUES (10201,17,0.25);
INSERT INTO "rd_budget_share" VALUES (10201,19,0.2);
INSERT INTO "rd_budget_share" VALUES (10201,18,0.7);
INSERT INTO "rd_budget_share" VALUES (10201,25,0.05);
INSERT INTO "rd_budget_share" VALUES (10201,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10201,10,0.7);
INSERT INTO "rd_budget_share" VALUES (10201,8,0.7);
INSERT INTO "rd_budget_share" VALUES (10201,9,1.75);
INSERT INTO "rd_budget_share" VALUES (10201,11,0.2);
INSERT INTO "rd_budget_share" VALUES (10201,16,1.05);
INSERT INTO "rd_budget_share" VALUES (10201,20,0.2);
INSERT INTO "rd_budget_share" VALUES (10301,1,2.5);
INSERT INTO "rd_budget_share" VALUES (10301,3,2.5);
INSERT INTO "rd_budget_share" VALUES (10301,5,1.4);
INSERT INTO "rd_budget_share" VALUES (10301,2,0.9);
INSERT INTO "rd_budget_share" VALUES (10301,4,0.3);
INSERT INTO "rd_budget_share" VALUES (10301,13,0.3);
INSERT INTO "rd_budget_share" VALUES (10301,17,0.2);
INSERT INTO "rd_budget_share" VALUES (10301,19,0.1);
INSERT INTO "rd_budget_share" VALUES (10301,18,0.4);
INSERT INTO "rd_budget_share" VALUES (10301,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10301,7,0.1);
INSERT INTO "rd_budget_share" VALUES (10301,10,0.3);
INSERT INTO "rd_budget_share" VALUES (10301,8,0.3);
INSERT INTO "rd_budget_share" VALUES (10301,9,0.3);
INSERT INTO "rd_budget_share" VALUES (10301,11,0.0);
INSERT INTO "rd_budget_share" VALUES (10301,16,0.2);
INSERT INTO "rd_budget_share" VALUES (10301,20,0.2);
INSERT INTO "rd_budget_share" VALUES (10302,1,2.5);
INSERT INTO "rd_budget_share" VALUES (10302,3,2.5);
INSERT INTO "rd_budget_share" VALUES (10302,5,2.0);
INSERT INTO "rd_budget_share" VALUES (10302,2,0.4);
INSERT INTO "rd_budget_share" VALUES (10302,4,0.8);
INSERT INTO "rd_budget_share" VALUES (10302,13,0.7);
INSERT INTO "rd_budget_share" VALUES (10302,17,0.2);
INSERT INTO "rd_budget_share" VALUES (10302,19,0.1);
INSERT INTO "rd_budget_share" VALUES (10302,18,0.5);
INSERT INTO "rd_budget_share" VALUES (10302,25,0.2);
INSERT INTO "rd_budget_share" VALUES (10302,7,0.1);
INSERT INTO "rd_budget_share" VALUES (10302,10,1.5);
INSERT INTO "rd_budget_share" VALUES (10302,8,0.9);
INSERT INTO "rd_budget_share" VALUES (10302,9,1.2);
INSERT INTO "rd_budget_share" VALUES (10302,11,0.2);
INSERT INTO "rd_budget_share" VALUES (10302,16,1.05);
INSERT INTO "rd_budget_share" VALUES (10302,20,0.4);
INSERT INTO "rd_budget_share" VALUES (10401,1,2.2);
INSERT INTO "rd_budget_share" VALUES (10401,3,2.2);
INSERT INTO "rd_budget_share" VALUES (10401,5,1.7);
INSERT INTO "rd_budget_share" VALUES (10401,2,0.15);
INSERT INTO "rd_budget_share" VALUES (10401,4,0.5);
INSERT INTO "rd_budget_share" VALUES (10401,13,0.5);
INSERT INTO "rd_budget_share" VALUES (10401,17,0.2);
INSERT INTO "rd_budget_share" VALUES (10401,19,0.2);
INSERT INTO "rd_budget_share" VALUES (10401,18,0.7);
INSERT INTO "rd_budget_share" VALUES (10401,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10401,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10401,10,0.7);
INSERT INTO "rd_budget_share" VALUES (10401,8,0.7);
INSERT INTO "rd_budget_share" VALUES (10401,9,1.7);
INSERT INTO "rd_budget_share" VALUES (10401,11,0.2);
INSERT INTO "rd_budget_share" VALUES (10401,16,1.05);
INSERT INTO "rd_budget_share" VALUES (10401,20,0.2);
INSERT INTO "rd_budget_share" VALUES (10402,1,1.1);
INSERT INTO "rd_budget_share" VALUES (10402,3,1.1);
INSERT INTO "rd_budget_share" VALUES (10402,5,1.0);
INSERT INTO "rd_budget_share" VALUES (10402,2,0.1);
INSERT INTO "rd_budget_share" VALUES (10402,4,0.1);
INSERT INTO "rd_budget_share" VALUES (10402,13,0.15);
INSERT INTO "rd_budget_share" VALUES (10402,17,0.1);
INSERT INTO "rd_budget_share" VALUES (10402,19,0.05);
INSERT INTO "rd_budget_share" VALUES (10402,18,0.5);
INSERT INTO "rd_budget_share" VALUES (10402,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10402,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10402,10,0.3);
INSERT INTO "rd_budget_share" VALUES (10402,8,0.3);
INSERT INTO "rd_budget_share" VALUES (10402,9,0.5);
INSERT INTO "rd_budget_share" VALUES (10402,11,0.1);
INSERT INTO "rd_budget_share" VALUES (10402,16,0.5);
INSERT INTO "rd_budget_share" VALUES (10402,20,0.4);
INSERT INTO "rd_budget_share" VALUES (10501,1,2.2);
INSERT INTO "rd_budget_share" VALUES (10501,3,2.2);
INSERT INTO "rd_budget_share" VALUES (10501,5,1.7);
INSERT INTO "rd_budget_share" VALUES (10501,2,0.15);
INSERT INTO "rd_budget_share" VALUES (10501,4,0.5);
INSERT INTO "rd_budget_share" VALUES (10501,13,0.5);
INSERT INTO "rd_budget_share" VALUES (10501,17,0.2);
INSERT INTO "rd_budget_share" VALUES (10501,19,0.2);
INSERT INTO "rd_budget_share" VALUES (10501,18,0.7);
INSERT INTO "rd_budget_share" VALUES (10501,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10501,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10501,10,0.7);
INSERT INTO "rd_budget_share" VALUES (10501,8,0.7);
INSERT INTO "rd_budget_share" VALUES (10501,9,1.7);
INSERT INTO "rd_budget_share" VALUES (10501,11,0.2);
INSERT INTO "rd_budget_share" VALUES (10501,16,1.05);
INSERT INTO "rd_budget_share" VALUES (10501,20,0.2);
INSERT INTO "rd_budget_share" VALUES (10502,1,1.1);
INSERT INTO "rd_budget_share" VALUES (10502,3,1.1);
INSERT INTO "rd_budget_share" VALUES (10502,5,1.0);
INSERT INTO "rd_budget_share" VALUES (10502,2,0.1);
INSERT INTO "rd_budget_share" VALUES (10502,4,0.1);
INSERT INTO "rd_budget_share" VALUES (10502,13,0.15);
INSERT INTO "rd_budget_share" VALUES (10502,17,0.1);
INSERT INTO "rd_budget_share" VALUES (10502,19,0.05);
INSERT INTO "rd_budget_share" VALUES (10502,18,0.5);
INSERT INTO "rd_budget_share" VALUES (10502,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10502,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10502,10,0.3);
INSERT INTO "rd_budget_share" VALUES (10502,8,0.3);
INSERT INTO "rd_budget_share" VALUES (10502,9,0.5);
INSERT INTO "rd_budget_share" VALUES (10502,11,0.1);
INSERT INTO "rd_budget_share" VALUES (10502,16,0.5);
INSERT INTO "rd_budget_share" VALUES (10502,20,0.4);
INSERT INTO "rd_budget_share" VALUES (10601,1,1.1);
INSERT INTO "rd_budget_share" VALUES (10601,3,1.1);
INSERT INTO "rd_budget_share" VALUES (10601,5,1.0);
INSERT INTO "rd_budget_share" VALUES (10601,2,0.1);
INSERT INTO "rd_budget_share" VALUES (10601,4,0.1);
INSERT INTO "rd_budget_share" VALUES (10601,13,0.15);
INSERT INTO "rd_budget_share" VALUES (10601,17,0.1);
INSERT INTO "rd_budget_share" VALUES (10601,19,0.05);
INSERT INTO "rd_budget_share" VALUES (10601,18,0.5);
INSERT INTO "rd_budget_share" VALUES (10601,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10601,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10601,10,0.3);
INSERT INTO "rd_budget_share" VALUES (10601,8,0.3);
INSERT INTO "rd_budget_share" VALUES (10601,9,0.5);
INSERT INTO "rd_budget_share" VALUES (10601,11,0.1);
INSERT INTO "rd_budget_share" VALUES (10601,16,0.5);
INSERT INTO "rd_budget_share" VALUES (10601,20,0.4);
INSERT INTO "rd_budget_share" VALUES (10701,1,1.5);
INSERT INTO "rd_budget_share" VALUES (10701,3,0.1);
INSERT INTO "rd_budget_share" VALUES (10701,5,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,2,2.25);
INSERT INTO "rd_budget_share" VALUES (10701,4,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,13,0.05);
INSERT INTO "rd_budget_share" VALUES (10701,17,0.1);
INSERT INTO "rd_budget_share" VALUES (10701,19,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,18,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,25,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,7,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,10,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,8,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,9,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,11,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,16,0.0);
INSERT INTO "rd_budget_share" VALUES (10701,20,0.05);
INSERT INTO "rd_budget_share" VALUES (10801,1,0.8);
INSERT INTO "rd_budget_share" VALUES (10801,3,0.05);
INSERT INTO "rd_budget_share" VALUES (10801,5,0.1);
INSERT INTO "rd_budget_share" VALUES (10801,2,1.4);
INSERT INTO "rd_budget_share" VALUES (10801,4,0.15);
INSERT INTO "rd_budget_share" VALUES (10801,13,0.1);
INSERT INTO "rd_budget_share" VALUES (10801,17,0.05);
INSERT INTO "rd_budget_share" VALUES (10801,19,0.0);
INSERT INTO "rd_budget_share" VALUES (10801,18,0.05);
INSERT INTO "rd_budget_share" VALUES (10801,25,0.0);
INSERT INTO "rd_budget_share" VALUES (10801,7,0.0);
INSERT INTO "rd_budget_share" VALUES (10801,10,0.05);
INSERT INTO "rd_budget_share" VALUES (10801,8,0.1);
INSERT INTO "rd_budget_share" VALUES (10801,9,0.0);
INSERT INTO "rd_budget_share" VALUES (10801,11,0.0);
INSERT INTO "rd_budget_share" VALUES (10801,16,0.0);
INSERT INTO "rd_budget_share" VALUES (10801,20,0.05);
INSERT INTO "rd_budget_share" VALUES (10901,1,0.5);
INSERT INTO "rd_budget_share" VALUES (10901,3,0.8);
INSERT INTO "rd_budget_share" VALUES (10901,5,0.1);
INSERT INTO "rd_budget_share" VALUES (10901,2,0.9);
INSERT INTO "rd_budget_share" VALUES (10901,4,0.35);
INSERT INTO "rd_budget_share" VALUES (10901,13,0.2);
INSERT INTO "rd_budget_share" VALUES (10901,17,0.1);
INSERT INTO "rd_budget_share" VALUES (10901,19,0.05);
INSERT INTO "rd_budget_share" VALUES (10901,18,0.5);
INSERT INTO "rd_budget_share" VALUES (10901,25,0.1);
INSERT INTO "rd_budget_share" VALUES (10901,7,0.05);
INSERT INTO "rd_budget_share" VALUES (10901,10,0.2);
INSERT INTO "rd_budget_share" VALUES (10901,8,0.3);
INSERT INTO "rd_budget_share" VALUES (10901,9,0.0);
INSERT INTO "rd_budget_share" VALUES (10901,11,0.0);
INSERT INTO "rd_budget_share" VALUES (10901,16,0.0);
INSERT INTO "rd_budget_share" VALUES (10901,20,0.05);
INSERT INTO "rd_budget_share" VALUES (11001,1,0.8);
INSERT INTO "rd_budget_share" VALUES (11001,3,0.05);
INSERT INTO "rd_budget_share" VALUES (11001,5,0.1);
INSERT INTO "rd_budget_share" VALUES (11001,2,1.4);
INSERT INTO "rd_budget_share" VALUES (11001,4,0.15);
INSERT INTO "rd_budget_share" VALUES (11001,13,0.1);
INSERT INTO "rd_budget_share" VALUES (11001,17,0.05);
INSERT INTO "rd_budget_share" VALUES (11001,19,0.0);
INSERT INTO "rd_budget_share" VALUES (11001,18,0.05);
INSERT INTO "rd_budget_share" VALUES (11001,25,0.0);
INSERT INTO "rd_budget_share" VALUES (11001,7,0.0);
INSERT INTO "rd_budget_share" VALUES (11001,10,0.05);
INSERT INTO "rd_budget_share" VALUES (11001,8,0.1);
INSERT INTO "rd_budget_share" VALUES (11001,9,0.0);
INSERT INTO "rd_budget_share" VALUES (11001,11,0.0);
INSERT INTO "rd_budget_share" VALUES (11001,16,0.0);
INSERT INTO "rd_budget_share" VALUES (11001,20,0.05);
INSERT INTO "rd_budget_share" VALUES (11201,1,2.2);
INSERT INTO "rd_budget_share" VALUES (11201,3,2.2);
INSERT INTO "rd_budget_share" VALUES (11201,5,1.7);
INSERT INTO "rd_budget_share" VALUES (11201,2,0.15);
INSERT INTO "rd_budget_share" VALUES (11201,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11201,13,0.5);
INSERT INTO "rd_budget_share" VALUES (11201,17,0.2);
INSERT INTO "rd_budget_share" VALUES (11201,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11201,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11201,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11201,7,0.1);
INSERT INTO "rd_budget_share" VALUES (11201,10,1.5);
INSERT INTO "rd_budget_share" VALUES (11201,8,0.9);
INSERT INTO "rd_budget_share" VALUES (11201,9,1.2);
INSERT INTO "rd_budget_share" VALUES (11201,11,0.4);
INSERT INTO "rd_budget_share" VALUES (11201,16,0.5);
INSERT INTO "rd_budget_share" VALUES (11201,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11202,1,2.2);
INSERT INTO "rd_budget_share" VALUES (11202,3,2.2);
INSERT INTO "rd_budget_share" VALUES (11202,5,1.7);
INSERT INTO "rd_budget_share" VALUES (11202,2,0.15);
INSERT INTO "rd_budget_share" VALUES (11202,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11202,13,0.5);
INSERT INTO "rd_budget_share" VALUES (11202,17,0.2);
INSERT INTO "rd_budget_share" VALUES (11202,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11202,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11202,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11202,7,0.1);
INSERT INTO "rd_budget_share" VALUES (11202,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11202,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11202,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11202,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11202,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11202,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11203,1,2.2);
INSERT INTO "rd_budget_share" VALUES (11203,3,2.2);
INSERT INTO "rd_budget_share" VALUES (11203,5,1.7);
INSERT INTO "rd_budget_share" VALUES (11203,2,0.15);
INSERT INTO "rd_budget_share" VALUES (11203,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11203,13,0.5);
INSERT INTO "rd_budget_share" VALUES (11203,17,0.2);
INSERT INTO "rd_budget_share" VALUES (11203,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11203,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11203,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11203,7,0.1);
INSERT INTO "rd_budget_share" VALUES (11203,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11203,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11203,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11203,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11203,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11203,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11204,1,2.7);
INSERT INTO "rd_budget_share" VALUES (11204,3,2.7);
INSERT INTO "rd_budget_share" VALUES (11204,5,1.5);
INSERT INTO "rd_budget_share" VALUES (11204,2,0.1);
INSERT INTO "rd_budget_share" VALUES (11204,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11204,13,0.4);
INSERT INTO "rd_budget_share" VALUES (11204,17,0.25);
INSERT INTO "rd_budget_share" VALUES (11204,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11204,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11204,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11204,7,0.05);
INSERT INTO "rd_budget_share" VALUES (11204,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11204,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11204,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11204,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11204,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11204,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11205,1,2.5);
INSERT INTO "rd_budget_share" VALUES (11205,3,2.5);
INSERT INTO "rd_budget_share" VALUES (11205,5,1.5);
INSERT INTO "rd_budget_share" VALUES (11205,2,0.1);
INSERT INTO "rd_budget_share" VALUES (11205,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11205,13,0.4);
INSERT INTO "rd_budget_share" VALUES (11205,17,0.25);
INSERT INTO "rd_budget_share" VALUES (11205,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11205,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11205,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11205,7,0.05);
INSERT INTO "rd_budget_share" VALUES (11205,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11205,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11205,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11205,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11205,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11205,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11206,1,2.5);
INSERT INTO "rd_budget_share" VALUES (11206,3,2.5);
INSERT INTO "rd_budget_share" VALUES (11206,5,1.5);
INSERT INTO "rd_budget_share" VALUES (11206,2,0.1);
INSERT INTO "rd_budget_share" VALUES (11206,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11206,13,0.4);
INSERT INTO "rd_budget_share" VALUES (11206,17,0.25);
INSERT INTO "rd_budget_share" VALUES (11206,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11206,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11206,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11206,7,0.05);
INSERT INTO "rd_budget_share" VALUES (11206,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11206,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11206,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11206,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11206,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11206,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11301,1,2.5);
INSERT INTO "rd_budget_share" VALUES (11301,3,2.5);
INSERT INTO "rd_budget_share" VALUES (11301,5,1.5);
INSERT INTO "rd_budget_share" VALUES (11301,2,0.1);
INSERT INTO "rd_budget_share" VALUES (11301,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11301,13,0.4);
INSERT INTO "rd_budget_share" VALUES (11301,17,0.25);
INSERT INTO "rd_budget_share" VALUES (11301,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11301,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11301,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11301,7,0.05);
INSERT INTO "rd_budget_share" VALUES (11301,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11301,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11301,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11301,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11301,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11301,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11401,1,2.5);
INSERT INTO "rd_budget_share" VALUES (11401,3,2.5);
INSERT INTO "rd_budget_share" VALUES (11401,5,1.5);
INSERT INTO "rd_budget_share" VALUES (11401,2,0.1);
INSERT INTO "rd_budget_share" VALUES (11401,4,0.5);
INSERT INTO "rd_budget_share" VALUES (11401,13,0.4);
INSERT INTO "rd_budget_share" VALUES (11401,17,0.25);
INSERT INTO "rd_budget_share" VALUES (11401,19,0.2);
INSERT INTO "rd_budget_share" VALUES (11401,18,0.7);
INSERT INTO "rd_budget_share" VALUES (11401,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11401,7,0.05);
INSERT INTO "rd_budget_share" VALUES (11401,10,0.7);
INSERT INTO "rd_budget_share" VALUES (11401,8,0.7);
INSERT INTO "rd_budget_share" VALUES (11401,9,1.7);
INSERT INTO "rd_budget_share" VALUES (11401,11,0.2);
INSERT INTO "rd_budget_share" VALUES (11401,16,1.05);
INSERT INTO "rd_budget_share" VALUES (11401,20,0.2);
INSERT INTO "rd_budget_share" VALUES (11501,1,0.9);
INSERT INTO "rd_budget_share" VALUES (11501,3,0.9);
INSERT INTO "rd_budget_share" VALUES (11501,5,1.0);
INSERT INTO "rd_budget_share" VALUES (11501,2,0.1);
INSERT INTO "rd_budget_share" VALUES (11501,4,0.1);
INSERT INTO "rd_budget_share" VALUES (11501,13,0.15);
INSERT INTO "rd_budget_share" VALUES (11501,17,0.1);
INSERT INTO "rd_budget_share" VALUES (11501,19,0.05);
INSERT INTO "rd_budget_share" VALUES (11501,18,0.5);
INSERT INTO "rd_budget_share" VALUES (11501,25,0.1);
INSERT INTO "rd_budget_share" VALUES (11501,7,0.05);
INSERT INTO "rd_budget_share" VALUES (11501,10,0.3);
INSERT INTO "rd_budget_share" VALUES (11501,8,0.3);
INSERT INTO "rd_budget_share" VALUES (11501,9,0.5);
INSERT INTO "rd_budget_share" VALUES (11501,11,0.1);
INSERT INTO "rd_budget_share" VALUES (11501,16,0.5);
INSERT INTO "rd_budget_share" VALUES (11501,20,0.4);
INSERT INTO "rd_budget_share" VALUES (11601,1,2.5);
INSERT INTO "rd_budget_share" VALUES (11601,3,0.1);
INSERT INTO "rd_budget_share" VALUES (11601,5,0.4);
INSERT INTO "rd_budget_share" VALUES (11601,2,0.15);
INSERT INTO "rd_budget_share" VALUES (11601,4,0.05);
INSERT INTO "rd_budget_share" VALUES (11601,13,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,17,0.2);
INSERT INTO "rd_budget_share" VALUES (11601,19,0.15);
INSERT INTO "rd_budget_share" VALUES (11601,18,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,25,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,7,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,10,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,8,0.02);
INSERT INTO "rd_budget_share" VALUES (11601,9,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,11,0.0);
INSERT INTO "rd_budget_share" VALUES (11601,16,0.01);
INSERT INTO "rd_budget_share" VALUES (11601,20,0.1);
INSERT INTO "rd_budget_share" VALUES (19901,1,2.5);
INSERT INTO "rd_budget_share" VALUES (19901,3,2.5);
INSERT INTO "rd_budget_share" VALUES (19901,5,1.5);
INSERT INTO "rd_budget_share" VALUES (19901,2,0.1);
INSERT INTO "rd_budget_share" VALUES (19901,4,0.5);
INSERT INTO "rd_budget_share" VALUES (19901,13,0.4);
INSERT INTO "rd_budget_share" VALUES (19901,17,0.15);
INSERT INTO "rd_budget_share" VALUES (19901,19,0.2);
INSERT INTO "rd_budget_share" VALUES (19901,18,0.7);
INSERT INTO "rd_budget_share" VALUES (19901,25,0.1);
INSERT INTO "rd_budget_share" VALUES (19901,7,0.05);
INSERT INTO "rd_budget_share" VALUES (19901,10,0.7);
INSERT INTO "rd_budget_share" VALUES (19901,8,0.7);
INSERT INTO "rd_budget_share" VALUES (19901,9,1.7);
INSERT INTO "rd_budget_share" VALUES (19901,11,0.2);
INSERT INTO "rd_budget_share" VALUES (19901,16,1.05);
INSERT INTO "rd_budget_share" VALUES (19901,20,0.2);
INSERT INTO "rd_budget_share" VALUES (20101,1,2.6);
INSERT INTO "rd_budget_share" VALUES (20101,3,2.6);
INSERT INTO "rd_budget_share" VALUES (20101,5,1.9);
INSERT INTO "rd_budget_share" VALUES (20101,2,0.25);
INSERT INTO "rd_budget_share" VALUES (20101,4,0.5);
INSERT INTO "rd_budget_share" VALUES (20101,13,0.5);
INSERT INTO "rd_budget_share" VALUES (20101,17,0.2);
INSERT INTO "rd_budget_share" VALUES (20101,19,0.1);
INSERT INTO "rd_budget_share" VALUES (20101,18,0.4);
INSERT INTO "rd_budget_share" VALUES (20101,25,0.1);
INSERT INTO "rd_budget_share" VALUES (20101,7,0.1);
INSERT INTO "rd_budget_share" VALUES (20101,10,0.9);
INSERT INTO "rd_budget_share" VALUES (20101,8,0.4);
INSERT INTO "rd_budget_share" VALUES (20101,9,0.8);
INSERT INTO "rd_budget_share" VALUES (20101,11,0.1);
INSERT INTO "rd_budget_share" VALUES (20101,16,1.05);
INSERT INTO "rd_budget_share" VALUES (20101,20,0.3);
INSERT INTO "rd_budget_share" VALUES (20801,1,1.6);
INSERT INTO "rd_budget_share" VALUES (20801,3,1.6);
INSERT INTO "rd_budget_share" VALUES (20801,5,1.0);
INSERT INTO "rd_budget_share" VALUES (20801,2,0.1);
INSERT INTO "rd_budget_share" VALUES (20801,4,0.3);
INSERT INTO "rd_budget_share" VALUES (20801,13,0.7);
INSERT INTO "rd_budget_share" VALUES (20801,17,0.1);
INSERT INTO "rd_budget_share" VALUES (20801,19,0.1);
INSERT INTO "rd_budget_share" VALUES (20801,18,0.3);
INSERT INTO "rd_budget_share" VALUES (20801,25,0.1);
INSERT INTO "rd_budget_share" VALUES (20801,7,0.1);
INSERT INTO "rd_budget_share" VALUES (20801,10,0.4);
INSERT INTO "rd_budget_share" VALUES (20801,8,1.0);
INSERT INTO "rd_budget_share" VALUES (20801,9,0.5);
INSERT INTO "rd_budget_share" VALUES (20801,11,0.1);
INSERT INTO "rd_budget_share" VALUES (20801,16,0.2);
INSERT INTO "rd_budget_share" VALUES (20801,20,0.1);
INSERT INTO "rd_budget_share" VALUES (30101,1,2.5);
INSERT INTO "rd_budget_share" VALUES (30101,3,2.5);
INSERT INTO "rd_budget_share" VALUES (30101,5,1.8);
INSERT INTO "rd_budget_share" VALUES (30101,2,0.2);
INSERT INTO "rd_budget_share" VALUES (30101,4,0.4);
INSERT INTO "rd_budget_share" VALUES (30101,13,0.6);
INSERT INTO "rd_budget_share" VALUES (30101,17,0.1);
INSERT INTO "rd_budget_share" VALUES (30101,19,0.2);
INSERT INTO "rd_budget_share" VALUES (30101,18,0.5);
INSERT INTO "rd_budget_share" VALUES (30101,25,0.05);
INSERT INTO "rd_budget_share" VALUES (30101,7,0.05);
INSERT INTO "rd_budget_share" VALUES (30101,10,0.6);
INSERT INTO "rd_budget_share" VALUES (30101,8,0.7);
INSERT INTO "rd_budget_share" VALUES (30101,9,1.2);
INSERT INTO "rd_budget_share" VALUES (30101,11,0.2);
INSERT INTO "rd_budget_share" VALUES (30101,16,0.95);
INSERT INTO "rd_budget_share" VALUES (30101,20,0.2);
INSERT INTO "rd_budget_share" VALUES (30301,1,2.5);
INSERT INTO "rd_budget_share" VALUES (30301,3,2.5);
INSERT INTO "rd_budget_share" VALUES (30301,5,2.0);
INSERT INTO "rd_budget_share" VALUES (30301,2,0.2);
INSERT INTO "rd_budget_share" VALUES (30301,4,0.4);
INSERT INTO "rd_budget_share" VALUES (30301,13,0.6);
INSERT INTO "rd_budget_share" VALUES (30301,17,0.1);
INSERT INTO "rd_budget_share" VALUES (30301,19,0.2);
INSERT INTO "rd_budget_share" VALUES (30301,18,0.7);
INSERT INTO "rd_budget_share" VALUES (30301,25,0.05);
INSERT INTO "rd_budget_share" VALUES (30301,7,0.05);
INSERT INTO "rd_budget_share" VALUES (30301,10,0.6);
INSERT INTO "rd_budget_share" VALUES (30301,8,0.7);
INSERT INTO "rd_budget_share" VALUES (30301,9,1.3);
INSERT INTO "rd_budget_share" VALUES (30301,11,0.2);
INSERT INTO "rd_budget_share" VALUES (30301,16,0.95);
INSERT INTO "rd_budget_share" VALUES (30301,20,0.2);
INSERT INTO "rd_budget_share" VALUES (40101,1,2.4);
INSERT INTO "rd_budget_share" VALUES (40101,3,2.4);
INSERT INTO "rd_budget_share" VALUES (40101,5,1.8);
INSERT INTO "rd_budget_share" VALUES (40101,2,0.2);
INSERT INTO "rd_budget_share" VALUES (40101,4,0.3);
INSERT INTO "rd_budget_share" VALUES (40101,13,0.5);
INSERT INTO "rd_budget_share" VALUES (40101,17,0.1);
INSERT INTO "rd_budget_share" VALUES (40101,19,0.15);
INSERT INTO "rd_budget_share" VALUES (40101,18,0.5);
INSERT INTO "rd_budget_share" VALUES (40101,25,0.05);
INSERT INTO "rd_budget_share" VALUES (40101,7,0.05);
INSERT INTO "rd_budget_share" VALUES (40101,10,0.55);
INSERT INTO "rd_budget_share" VALUES (40101,8,0.6);
INSERT INTO "rd_budget_share" VALUES (40101,9,1.1);
INSERT INTO "rd_budget_share" VALUES (40101,11,0.2);
INSERT INTO "rd_budget_share" VALUES (40101,16,1.05);
INSERT INTO "rd_budget_share" VALUES (40101,20,0.15);
INSERT INTO "rd_budget_share" VALUES (40301,1,2.4);
INSERT INTO "rd_budget_share" VALUES (40301,3,2.4);
INSERT INTO "rd_budget_share" VALUES (40301,5,1.8);
INSERT INTO "rd_budget_share" VALUES (40301,2,0.2);
INSERT INTO "rd_budget_share" VALUES (40301,4,0.3);
INSERT INTO "rd_budget_share" VALUES (40301,13,0.5);
INSERT INTO "rd_budget_share" VALUES (40301,17,0.1);
INSERT INTO "rd_budget_share" VALUES (40301,19,0.15);
INSERT INTO "rd_budget_share" VALUES (40301,18,0.5);
INSERT INTO "rd_budget_share" VALUES (40301,25,0.05);
INSERT INTO "rd_budget_share" VALUES (40301,7,0.05);
INSERT INTO "rd_budget_share" VALUES (40301,10,0.55);
INSERT INTO "rd_budget_share" VALUES (40301,8,0.6);
INSERT INTO "rd_budget_share" VALUES (40301,9,1.1);
INSERT INTO "rd_budget_share" VALUES (40301,11,0.2);
INSERT INTO "rd_budget_share" VALUES (40301,16,1.05);
INSERT INTO "rd_budget_share" VALUES (40301,20,0.15);
INSERT INTO "rd_budget_share" VALUES (60101,1,2.8);
INSERT INTO "rd_budget_share" VALUES (60101,3,2.8);
INSERT INTO "rd_budget_share" VALUES (60101,5,1.8);
INSERT INTO "rd_budget_share" VALUES (60101,2,0.2);
INSERT INTO "rd_budget_share" VALUES (60101,4,0.55);
INSERT INTO "rd_budget_share" VALUES (60101,13,0.4);
INSERT INTO "rd_budget_share" VALUES (60101,17,0.15);
INSERT INTO "rd_budget_share" VALUES (60101,19,0.2);
INSERT INTO "rd_budget_share" VALUES (60101,18,0.8);
INSERT INTO "rd_budget_share" VALUES (60101,25,0.1);
INSERT INTO "rd_budget_share" VALUES (60101,7,0.1);
INSERT INTO "rd_budget_share" VALUES (60101,10,0.85);
INSERT INTO "rd_budget_share" VALUES (60101,8,0.6);
INSERT INTO "rd_budget_share" VALUES (60101,9,0.5);
INSERT INTO "rd_budget_share" VALUES (60101,11,0.1);
INSERT INTO "rd_budget_share" VALUES (60101,16,0.45);
INSERT INTO "rd_budget_share" VALUES (60101,20,0.1);
INSERT INTO "rd_budget_share" VALUES (70101,1,2.5);
INSERT INTO "rd_budget_share" VALUES (70101,3,2.5);
INSERT INTO "rd_budget_share" VALUES (70101,5,1.8);
INSERT INTO "rd_budget_share" VALUES (70101,2,0.8);
INSERT INTO "rd_budget_share" VALUES (70101,4,0.25);
INSERT INTO "rd_budget_share" VALUES (70101,13,0.4);
INSERT INTO "rd_budget_share" VALUES (70101,17,0.1);
INSERT INTO "rd_budget_share" VALUES (70101,19,1.1);
INSERT INTO "rd_budget_share" VALUES (70101,18,0.7);
INSERT INTO "rd_budget_share" VALUES (70101,25,0.1);
INSERT INTO "rd_budget_share" VALUES (70101,7,0.1);
INSERT INTO "rd_budget_share" VALUES (70101,10,0.6);
INSERT INTO "rd_budget_share" VALUES (70101,8,0.7);
INSERT INTO "rd_budget_share" VALUES (70101,9,1.8);
INSERT INTO "rd_budget_share" VALUES (70101,11,0.1);
INSERT INTO "rd_budget_share" VALUES (70101,16,0.1);
INSERT INTO "rd_budget_share" VALUES (70101,20,0.2);
INSERT INTO "rd_budget_share" VALUES (80101,1,2.45);
INSERT INTO "rd_budget_share" VALUES (80101,3,2.45);
INSERT INTO "rd_budget_share" VALUES (80101,5,1.9);
INSERT INTO "rd_budget_share" VALUES (80101,2,0.2);
INSERT INTO "rd_budget_share" VALUES (80101,4,0.35);
INSERT INTO "rd_budget_share" VALUES (80101,13,0.55);
INSERT INTO "rd_budget_share" VALUES (80101,17,0.1);
INSERT INTO "rd_budget_share" VALUES (80101,19,0.2);
INSERT INTO "rd_budget_share" VALUES (80101,18,0.6);
INSERT INTO "rd_budget_share" VALUES (80101,25,0.1);
INSERT INTO "rd_budget_share" VALUES (80101,7,0.1);
INSERT INTO "rd_budget_share" VALUES (80101,10,0.6);
INSERT INTO "rd_budget_share" VALUES (80101,8,0.65);
INSERT INTO "rd_budget_share" VALUES (80101,9,1.2);
INSERT INTO "rd_budget_share" VALUES (80101,11,0.2);
INSERT INTO "rd_budget_share" VALUES (80101,16,1.1);
INSERT INTO "rd_budget_share" VALUES (80101,20,0.2);
INSERT INTO "rd_budget_share" VALUES (90101,1,2.4);
INSERT INTO "rd_budget_share" VALUES (90101,3,2.4);
INSERT INTO "rd_budget_share" VALUES (90101,5,1.5);
INSERT INTO "rd_budget_share" VALUES (90101,2,0.2);
INSERT INTO "rd_budget_share" VALUES (90101,4,1.1);
INSERT INTO "rd_budget_share" VALUES (90101,13,0.4);
INSERT INTO "rd_budget_share" VALUES (90101,17,0.2);
INSERT INTO "rd_budget_share" VALUES (90101,19,0.2);
INSERT INTO "rd_budget_share" VALUES (90101,18,0.7);
INSERT INTO "rd_budget_share" VALUES (90101,25,0.1);
INSERT INTO "rd_budget_share" VALUES (90101,7,0.1);
INSERT INTO "rd_budget_share" VALUES (90101,10,0.7);
INSERT INTO "rd_budget_share" VALUES (90101,8,0.7);
INSERT INTO "rd_budget_share" VALUES (90101,9,0.5);
INSERT INTO "rd_budget_share" VALUES (90101,11,0.2);
INSERT INTO "rd_budget_share" VALUES (90101,16,0.8);
INSERT INTO "rd_budget_share" VALUES (90101,20,0.1);
INSERT INTO "system" VALUES (1,'Кабели, провода и изделия для прокладки кабеля',1,1,1);
INSERT INTO "system" VALUES (2,'Энергетическое оборудование',1,1,1);
INSERT INTO "system" VALUES (3,'Металлоконструкции',1,1,2);
INSERT INTO "system" VALUES (4,'Кабели, провода и изделия для прокладки кабеля',1,1,2);
INSERT INTO "system" VALUES (5,'Светотехнические изделия',1,1,2);
INSERT INTO "system" VALUES (6,'Управление освещением',1,1,2);
INSERT INTO "system" VALUES (7,'Щитовое оборудование',1,1,3);
INSERT INTO "system" VALUES (8,'Силовое электрооборудование',1,1,3);
INSERT INTO "system" VALUES (9,'Измерительная аппаратура',1,1,3);
INSERT INTO "system" VALUES (10,'Модульное оборудование',1,1,3);
INSERT INTO "system" VALUES (11,'Изделия электроустановочные',1,1,3);
INSERT INTO "system" VALUES (12,'Системы для прокладки кабеля',1,1,3);
INSERT INTO "system" VALUES (13,'Электрообогрев',1,1,3);
INSERT INTO "system" VALUES (14,'Огнезащита',1,1,3);
INSERT INTO "system" VALUES (15,'Шинопровод',1,1,3);
INSERT INTO "system" VALUES (16,'Щитовое оборудование',1,1,4);
INSERT INTO "system" VALUES (17,'Модульное оборудование',1,1,4);
INSERT INTO "system" VALUES (18,'Светотехнические изделия',1,1,4);
INSERT INTO "system" VALUES (19,'Управление освещением',1,1,4);
INSERT INTO "system" VALUES (20,'Система молниезащиты',1,1,5);
INSERT INTO "system" VALUES (21,'Система заземления',1,1,5);
INSERT INTO "system" VALUES (22,'Противопожарный водопровод',2,2,6);
INSERT INTO "system" VALUES (23,'Противопожарная защита',2,2,7);
INSERT INTO "system" VALUES (24,'Насосное оборудование',2,2,8);
INSERT INTO "system" VALUES (25,'Водозабор и напорная канализация',2,2,8);
INSERT INTO "system" VALUES (26,'Кровельные системы',2,2,8);
INSERT INTO "system" VALUES (27,'Хозяйственно-питьевой водопровод',2,2,9);
INSERT INTO "system" VALUES (28,'Горячее водоснабжение',2,2,9);
INSERT INTO "system" VALUES (29,'Внутренние сети канализации',2,2,9);
INSERT INTO "system" VALUES (30,'Отопление',2,3,10);
INSERT INTO "system" VALUES (31,'Вентиляция и кондиционирование',2,3,10);
INSERT INTO "system" VALUES (32,'БТП блочные тепловые пункты',2,3,11);
INSERT INTO "system" VALUES (33,'ИТП индивидуальные тепловые пункты',2,3,11);
INSERT INTO "system" VALUES (34,'Узлы учета и насосное оборудование',2,3,11);
INSERT INTO "system" VALUES (35,'Телефония',3,4,12);
INSERT INTO "system" VALUES (36,'Радиофикация',3,4,12);
INSERT INTO "system" VALUES (37,'Телеприем',3,4,12);
INSERT INTO "system" VALUES (38,'Телекоммуникационные шкафы',3,4,13);
INSERT INTO "system" VALUES (39,'Кабельно-проводниковая продукция',3,4,13);
INSERT INTO "system" VALUES (40,'Системы преобразования сред/Коммутация',3,4,13);
INSERT INTO "system" VALUES (41,'Автоматизированная система управления и диспетчеризации',3,4,14);
INSERT INTO "system" VALUES (42,'Автоматическая система контроля загазованности',3,4,15);
INSERT INTO "system" VALUES (43,'Комплексная автоматизация (при объединении АИС и АТП)',3,4,16);
INSERT INTO "system" VALUES (44,'Система видеонаблюдения',3,4,17);
INSERT INTO "system" VALUES (45,'Видеосерверы, СХД',3,4,17);
INSERT INTO "system" VALUES (46,'Инфраструктурные элементы системы',3,4,17);
INSERT INTO "system" VALUES (47,'Охрана периметра',3,4,18);
INSERT INTO "system" VALUES (48,'Охрана объектовая',3,4,18);
INSERT INTO "system" VALUES (49,'Система контроля и управления доступом; Система учета рабочего времени',3,4,19);
INSERT INTO "system" VALUES (50,'Устройства ограничения доступа',3,4,19);
INSERT INTO "system" VALUES (51,'Сопутствующие товары',3,4,19);
INSERT INTO "system" VALUES (52,'Кассовое оборудованиие',3,4,20);
INSERT INTO "system" VALUES (53,'Банковское оборудование',3,4,20);
INSERT INTO "system" VALUES (54,'Оборудование для маркировки',3,4,20);
INSERT INTO "system" VALUES (55,'Оборудование для торгового зала',3,4,20);
INSERT INTO "system" VALUES (56,'Коммутаторы, промышленные коммутаторы, маршрутизаторы, аксессуары и сопутствующее оборудование',3,4,21);
INSERT INTO "system" VALUES (57,'Серверы для ЦОД, серверы времени, терминальные серверы, серверы баз данных, СХД, АРМ, комплектующие для серверов',3,4,22);
INSERT INTO "system" VALUES (58,'Персональные компьютеры, ноутбуки, моноблоки, планшеты, смартфоны, в том числе защищенные, мониторы, периферия, печатная техника, фототехника, комплектующие для ПК',3,4,22);
INSERT INTO "system" VALUES (59,'Системное ПО, офсиное ПО, прикладное ПО, базы-данных, 1С, ключи активации и верификации',3,4,23);
INSERT INTO "system" VALUES (60,'Терминалы, серверы ВКС, видеокамеры трансляции, дисплеи, микрофоны, спикрефоны, динамики, ПО ВКС',3,4,24);
INSERT INTO "system" VALUES (61,'Проекторы, экраны, ЖК-дисплеи, OLED-панел, видеостены, видеоконтроллеры, панели управления, коммутационный кабель аудио- видеосигнала',3,4,24);
INSERT INTO "system" VALUES (62,'Автоматическая пожарная сигнализация',3,5,25);
INSERT INTO "system" VALUES (63,'Система оповещения и управления эвакуацией',3,5,26);
INSERT INTO "system" VALUES (64,'Огнестойкая кабельная линия',3,5,27);
INSERT INTO "system" VALUES (65,'Огнестойкая кабельная линия',3,5,28);
INSERT INTO "system" VALUES (66,'Системы дымоудаления; Системы подпора давления воздуха; Системы управления инженерными сетями;',3,5,29);
INSERT INTO "system" VALUES (67,'Системы пожаротушения',3,5,30);
INSERT INTO "system" VALUES (68,'Противопожарная защита',3,5,31);
COMMIT;
